### ISSUE TITLE
Do you have video resource?

### ISSUE THREAD

**Issue by ghost** [Anwarvic/Dan-Jurafsky--Chris-Manning--Natural-Language-Processing#1]
The youtube video have been deleted, the download link is not working...

**Comment by Anwarvic** [comment]
Yes, the youtube channel was deleted, but I tried the magnet link and it is working fine.

**Comment by Anwarvic** [comment]
@willwinworld, another [playlist](https://www.youtube.com/playlist?list=PLQiyVNMpDLKnZYBTUOlSI9mi9wAErFtFm) was created on YouTube containing the whole course
